markdown: kramdown
title: "cory malnarick :: designer"
description: "Cory Malnarick is a designer based in San Francisco, IL. His primary focus is in human-centered experience design for software and service products. He has worked with General Assembly, World Bicycle Relief, Torque Digital, and VSA Partners."
about: ""
location: ""
email: hi@coryis.digital
twitter_username: lostmonster
baseurl: ""
url: "http://lostmonster.github.io" # replace by your site's url